name: Selenium CI with Maven

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    # Checkout repo
    - name: Checkout Repository
      uses: actions/checkout@v4

    # Setup JDK 1.8
    - name: Set up JDK 1.8
      uses: actions/setup-java@v4
      with:
        java-version: '8'
        distribution: 'temurin'
        cache: maven

    # Build with Maven (compile + package + run tests)
    - name: Build with Maven
      run: mvn clean install -B

    # Run Cucumber Tests using Runner file
    - name: Run Cucumber Tests
      run: mvn test -Dcucumber.options="--plugin pretty"

    # (Optional) Upload test reports as artifact
    - name: Upload Test Reports
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: cucumber-reports
        path: target/cucumber-reports/
